package multi_Threading;

public class I_Thread_Priority {

	public static void main(String[] args) throws InterruptedException {
		
/*
 * Thread Priorities
    Threads can be assigned priorities to influence scheduling decisions. Higher priority threads are given 
    preference by the thread scheduler.
    
 * Every thread in java has some priority it may be default priority generated by JVM or customized 
          priority provided by programmer.
           
 * The valid range of Thread priority is 1 to 10, where 1 is Min priority and 10 is Max priority.
 
 * Thread class defines the following constant to represent some standard priority ::
   ✔️ Thread.MIN_PRIORITY = 1      ✔️ Thread.NORM_PRIORITY = 5     ✔️ Thread.MAX_PRIORITY = 10
  
 * Thread scheduler will use priorities while allocating processor, the thread which is having highest
     priority will get a chance first.
 * If two threads having same priority then we can't expect exact execution order it depends on thread scheduler.

 * Thread class defines the following methods to get and set priority of a thread::
   ⭕ public final int getPriority
   ⭕ public final void setPriority(int p) = Allowed values range 1 to 10, 
   													otherwise runtimeException: IllegalArgumentEception.
 * ex:: t.setPriority(7);  ✔️ valid
        t.setPriority(17); ❌ RE: IllegalArgumentException
  
 * 	DefaultPriority::  
 *      The default priority only for the main thread is 5 , but for all remaining threads default priority
         will be inherited from parent to child that is what ever priority parent thread has the same
          priority will be there for the child thread.
    
 *   
 * NOTE:: Some platforms won't provide proper support for thread priorities. Ex: win7
 * 
  	
 */

		
	   System.out.println(Thread.currentThread().getPriority());  // main thread priority
	   
//		Thread.currentThread().setPriority(15); RE: IllegalArgumentException
	   
/*
 * if we comment in line no 50 then both main and child thread  have same priority is a 5, hence we can't
	  expect execution order and exact output.
 * if we are not commenting this line then main thread has a priority 5 and child thread has the priority 10
	  hence, child thread will get the chance first followed by main thread in this case output is
		  "child thread" 10 times followed by "main thread" 10 times.
*/	   
	 Thread.currentThread().setPriority(7); // now main thread has 7 priority
		
		myThread t = new myThread();  // parent thread is main thread and it create child thread
		System.out.println(t.getPriority()); // inherit parent priority by default
		t.setPriority(10);
		System.out.println(t.getPriority());  // now child has own priority is 10
		t.start();
		
		
		for(int i = 0;i<10;i++) {
			System.out.println("Parent thread");
		}
		
	}

}




class myThread extends Thread{
	public void run() {
		for(int i=0;i<10;i++) {
			System.out.println("Child thread");
		}
	}
}

// Thread priority in Java is a scheduling hint (1–10) given to the OS scheduler to influence execution
// order. It does not guarantee execution precedence. Priority is inherited from the parent thread and
// mapped to OS-level priority. Overuse can cause starvation and is generally not recommended for 
//controlling program logic.